<?php
/******************************************************************************
 * NINA VIỆT NAM
 * Email: nina@nina.vn
 * Website: nina.vn
 * Version: 1.0
 * Đây là tài sản của CÔNG TY TNHH TM DV NINA. Vui lòng không sử dụng khi chưa được phép.
 */

return [
    'logo' => [
        'title_main' => "Logo",
        'kind' => 'static',
        'title' => true,
        'desc' => false,
        'desc_cke' => false,
        'link' => false,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 480,
        'height' => 76,
        'thumb' => '480x76x2',
    ],
    // 'banner' => [
    //     'title_main' => "Banner",
    //     'kind' => 'static',
    //     'desc' => false,
    //     'desc_cke' => false,
    //     'link' => true,
    //     'status' => ["hienthi" => "Hiển thị"],
    //     'images' => true,
    //     'width' => 520,
    //     'height' => 90,
    //     'thumb' => '520x90x2',
    // ],
    'banner-visao' => [
        'title_main' => "Banner vì sao",
        'kind' => 'static',
        'desc' => false,
        'desc_cke' => false,
        'link' => true,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 560,
        'height' => 590,
        'thumb' => '560x590x2',
    ],
    'favicon' => [
        'title_main' => "Favicon",
        'kind' => 'static',
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 48,
        'height' => 48,
        'thumb' => '48x48x2',
    ],
    'slide' => [
        'title_main' => "Slideshow",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 5,
        'title' => true,
        'images' => true,
        'show_images' => true,
        'gallery' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'width' => 1366,
        'height' => 500,
        'thumb' => '1366x500x1',
    ],
    'social' => [
        'title_main' => "Mạng xã hội",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 4,
        'show_images' => true,
        'images' => true,
        'avatar' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'width' => 40,
        'height' => 40,
        'thumb' => '40x40x1',
    ],
    'chung-nhan' => [
        'title_main' => "Chứng nhận",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 4,
        'show_images' => true,
        'images' => true,
        'avatar' => true,
        'link' => false,
        'name' => true,
        'desc' => false,
        'width' => 380,
        'height' => 400,
        'thumb' => '100x200x2',
    ],
    'thu-vien' => [
        'title_main' => "Thư viện ảnh",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 4,
        'show_images' => true,
        'images' => true,
        'avatar' => true,
        'link' => false,
        'name' => true,
        'desc' => false,
        'width' => 500,
        'height' => 500,
        'thumb' => '200x200x1',
    ]
    // 'watermark_product' => [
    //     'title_main' => "Con dấu sản phẩm",
    //     'kind' => 'static',
    //     'watermark' =>true,
    //     'desc' => false,
    //     'title' => false,
    //     'desc_cke' => false,
    //     'link' => false,
    //     'status' => ["hienthi" => "Hiển thị"],
    //     'images' => true,
    //     'width' => 70,
    //     'height' => 70,
    //     'thumb' => '70x70x1',
    // ]
];